project:
  type: website
  output-dir: _site

website:
  title: "Bill Splitter - MDS"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: reference/index.qmd
        text: Reference
      - href: reflection.qmd
        text: Reflection

# tell quarto to read the generated sidebar
metadata-files:
  - reference/_sidebar.yml

# tell quarto to read the generated styles
format:
  html:
    css:
      - reference/_styles-quartodoc.css

quartodoc:
  # the name used to import the package you want to create reference docs for
  package: billsplittermds

  # write sidebar and style data
  sidebar: reference/_sidebar.yml
  css: reference/_styles-quartodoc.css

  sections:
    - title: Bill Splitter Functions
      desc: A package of functions to split bills and manage transfers.
      contents:
        # the functions being documented in the package.
        # you can refer to anything: class methods, modules, etc..
        - load_validate_data
        - split_by_item
        - individual_total_payments
        - amount_to_transfer
